#=============================================#
#                 HAMZA AMIN                  #
#     𝗠𝗨𝗟𝗧𝗜𝗗𝗘𝗩𝗜𝗖𝗘 𝗪𝗛𝗔𝗧𝗦𝗔𝗣𝗣 𝗨𝗦𝗘𝗥 𝗕𝗢𝗧       #
#=============================================#
# 
#    * @project_name : HAMZA-Md
#    * @author : @HAMZA
#    * @youtube : https://chat.whatsapp.com/G0RAGHE329OBUE0pfoeZNV
#    * @description : HAMZA-Md ,A Multi-functional whatsapp bot md https://chat.whatsapp.com/G0RAGHE329OBUE0pfoeZNV .
#    * @version 9.9.0
# 
# Don't change this [ /SuhailTechInfo/ ] name!
# Change from below link, else bot not works!

 

FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/SuhailTechInfo/Suhail-Md /root/Suhail
WORKDIR /root/Suhail/
RUN npm install
EXPOSE 8000
CMD ["npm","start" ] 
